### Product Index Action
GET http://localhost:3000/products.json

### Product Show Action
GET http://localhost:3000/products/3.json

### Product Create Action
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MjkwMDB9.ZfONEMGoQJIN6ibC7zWsUJAjAQVXEcU-qisuULaGqlY
Content-Type: application/json

{
  "name": "Sharpie",
  "price": 1,
  "description": "A black marker than can be used to go over mistakes and not show them or write in big fonts.",
  "supplier_id": 2
}

### Product Update Action
PATCH http://localhost:3000/products/11.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MjkwMDB9.ZfONEMGoQJIN6ibC7zWsUJAjAQVXEcU-qisuULaGqlY
Content-Type: application/json

{
  "image_url": "an_image.png"
}

### Product Destroy Action
DELETE  http://localhost:3000/products/13.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjI4MzYzMTR9.3pKW2iBaSrzgJfiKDuPJIYJSWZLjpDzllhHXJf5l7rM

### Supplier Index Action
GET http://localhost:3000/suppliers.json

### Supplier Show Action
GET http://localhost:3000/suppliers/1.json

### Supplier Create Action
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Awazon",
  "email": "awazon@gmail.com",
  "phone_number": "345-347-2375"
}

### Supplier Update Action
PATCH http://localhost:3000/suppliers/4.json


### Users Create (Signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Wally",
  "email": "wally@test.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": true
}

### Order Index Action
GET http://localhost:3000/orders.json
Authorization: Bearer 

### Order Show Action
GET http://localhost:3000/orders/3.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MjkwMDB9.ZfONEMGoQJIN6ibC7zWsUJAjAQVXEcU-qisuULaGqlY

### Order Create Action
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MjkwMDB9.ZfONEMGoQJIN6ibC7zWsUJAjAQVXEcU-qisuULaGqlY

{
  "product_id": 1,
  "quantity": 1
}

### Sessions Create Action
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "wally@test.com",
  "password": "password"
}