### Product Index Action
GET http://localhost:3000/products.json

### Product Show Action
GET http://localhost:3000/products/3.json

### Product Create Action
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test_name",
  "price": 3,
  "image_url": "test_url",
  "description": "test_description"
}

### Product Update Action
PATCH http://localhost:3000/products/11.json
Content-Type: application/json

{
  "image_url": "an_image.png"
}

### Product Destroy Action
DELETE  http://localhost:3000/products/8.json

### Supplier Index Action
GET http://localhost:3000/suppliers.json

### Supplier Show Action
GET http://localhost:3000/suppliers/1.json

### Supplier Create Action
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Awazon",
  "email": "awazon@gmail.com",
  "phone_number": "345-347-2375"
}

### Supplier Update Action
PATCH http://localhost:3000/suppliers/4.json